Replace requests to Traffic by requests to Distance API
Woosmap/geofencing-core-android-sdk pull request #10
Opened 2023-04-18 06:11 UTC by strider1981

# Description
## Issue
closes #9 

## What
Stop request to Traffic API and replace them by Distance API requests with proper parameters.

## How
1. Added additional parameter `considerTrafic` in `distanceAPI` of `PositionManager` class. 
2. If `considerTrafic` is `true` then add additional parameter `departure_time` (value is set to `now`) to distance API.

## Related PRs
None

# Testing
## Automated tests
- [ ] Unit Tests cover the change
- [ ] Smoke Tests cover the change  
- [x] Manual Tests cover the change  

## Steps to test or reproduce

# Deployment
## Strategy
- [x] This is a standard deployment

## Migrations

No.

2023-04-18 11:23 UTC, sameerdhulap requested changes

2023-04-18 11:23 UTC, sameerdhulap commented on gradle.properties
> +VERSION_NAME=core_beta2.14
This should be release version

2023-04-18 11:23 UTC, sameerdhulap commented on woosmapgeofencingcore/src/main/java/com/webgeoservices/woosmapgeofencingcore/WoosmapSettingsCore.java
> +    public static String DistanceAPIWithTrafficUrl = "%s/distance/distancematrix/json?mode=%s&units=%s&language=%s&origins=%s,%s&destinations=%s&private_key=%s&departure_time=now&elements=duration_di
How are you managing method parameters?
https://developers.woosmap.com/api-reference/#operation/getDistanceMatrix

2023-04-19 09:01 UTC, sameerdhulap approved these changes

2023-04-21 11:00 UTC, sameerdhulap approved these changes

2023-04-21 11:05 UTC, sameerdhulap approved these changes

2023-04-28 14:24 UTC, lpernelle-wgs requested changes

2023-04-28 14:24 UTC, lpernelle-wgs commented on woosmapgeofencingcore/src/main/java/com/webgeoservices/woosmapgeofencingcore/WoosmapSettingsCore.java
> +    public static boolean getDistanceWithTrafic(){
```suggestion
    public static boolean getDistanceWithTraffic(){
```

2023-05-02 14:33 UTC, merged